apiVersion: batch/v1
kind: Job
metadata:
  name: data-ingestion
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ingestion
          image: data-ingestion
          imagePullPolicy: Never
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
