apiVersion: batch/v1
kind: Job
metadata:
  name: data-aggregator
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: aggregator
          image: data-aggregator:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
