apiVersion: batch/v1
kind: Job
metadata:
  name: data-analysis
spec:
  completions: 3
  parallelism: 2           # 👈 Minikube realista
  completionMode: Indexed  # 👈 CLAVE
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: analysis
          image: data-analysis
          imagePullPolicy: IfNotPresent
          env:
            - name: TOTAL_WORKERS
              value: "3"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          volumeMounts:
            - name: data-volume
              mountPath: /data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
